export default {
  "text.b": "B",
  "text.bold": "Bold",
  "text.breadcrumb": "Breadcrumb",
  "text.bullets": "Bullets",
  "text.c": "C#",
  "text.camera-api-is-not-available-in-this-browser": "Camera API is not available in this browser.",
  "text.camera-permission-was-denied": "Camera permission was denied.",
  "text.captured": "Captured:",
  "text.cast": "Cast",
  "text.clear-formatting": "Clear formatting",
  "text.clear-text": "Clear text",
  "text.close-overflow-menu": "Close overflow menu",
  "text.command-bar": "Command bar",
  "text.copy": "Copy",
  "text.cut": "Cut",
  "text.g": "G",
  "text.hue": "Hue",
  "text.integrated-camera": "Integrated camera",
  "text.italic": "Italic",
  "text.more": "More",
  "text.more-options": "More options",
  "text.navigationview": "NavigationView",
  "text.numbering": "Numbering",
  "text.off": "Off",
  "text.on": "On",
  "sample.opacity": "Opacity",
  "text.paste": "Paste",
  "text.pause": "Pause",
  "text.play": "Play",
  "text.r": "R",
  "text.redo": "Redo",
  "text.requesting-camera-permission": "Requesting camera permission...",
  "text.reveal-password": "Reveal password",
  "text.scroll-left": "Scroll left",
  "text.scroll-right": "Scroll right",
  "text.select": "Select...",
  "text.select-all": "Select all",
  "text.settings": "Settings",
  "text.source-code": "Source code",
  "text.saturation": "Saturation",
  "text.submit-query": "Submit query",
  "text.unable-to-start-the-camera": "Unable to start the camera.",
  "text.underline": "Underline",
  "text.undo": "Undo",
  "text.unmute": "Unmute",
  "text.value": "Value",
  "text.volume": "Volume",
  "text.vue": "Vue",
  "text.xaml": "XAML"
};
