// build-md.mjs —— 构建期 Markdown 文章生成器
// 读取 src/content 下的 .md 文件，解析 frontmatter（chapter / section / title / icon /
// chapterName / chapterIcon / summary / keywords），用 markdown-it 渲染为 HTML，
// 并提取纯文本供搜索，生成 src/data/markdownArticles.ts（被 App / 文章页 / 搜索统一引用）。
//
// 命名约定（贴合本站「章 / 节」体系）：
//   chapter    = 第几「章」（顶层分组，如 第一卷→第一章）
//   section    = 该章内的第几「节」（单篇文章，如 第一章→第一节）
//   chapterName= 该章在导航显示的的名字（如「开箱与初见」），可只在一篇里写
//   chapterIcon= 该章在导航显示的图标（可选）
//
// 运行：npm run build:md  （dev / build 前会自动执行）
// 该文件为 Node 脚本，不参与 vue-tsc 类型检查；生成的 .ts 才会被类型检查。

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import MarkdownIt from 'markdown-it';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const contentDir = path.join(root, 'src', 'content');
const outFile = path.join(root, 'src', 'data', 'markdownArticles.ts');

const md = new MarkdownIt({
  html: true,        // 允许在 md 中嵌入原始 HTML（图片/视频/卡片）
  linkify: true,     // 自动识别链接
  typographer: true, // 智能引号/省略号
  breaks: false,     // 末尾换行不强制 <br>
});

// 递归收集目录下所有 .md 文件
function walk(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith('.md')) out.push(full);
  }
  return out;
}

// 支持在 .md 的 frontmatter 里用两种写法写图标码点：
//   1) 带反斜杠：  icon: '\uE80F'   （和 .ts 写法一致）
//   2) 裸写法：    icon: 'uE80F'    （不带反斜杠，更省事）
// 原因：YAML 单引号字符串不会解析 \uXXXX（会被当成字面字符），
// 而 .ts 里是 JS 编译器帮你转义的。这里在构建期手动补上这一步，
// 让 .md 也能用这两种写法。只作用于图标字段（icon / chapterIcon）。
function decodeJsEscapes(str) {
  return String(str)
    // 1) 先处理带反斜杠的 \uXXXX
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) =>
      String.fromCharCode(parseInt(hex, 16)),
    )
    // 2) 再处理裸写法的 uXXXX（不带反斜杠）。
    //    用前后边界（不能是十六进制数字 / 反斜杠），避免误伤普通文本里的 "u + 数字"。
    .replace(/(?<![0-9a-fA-F\\])u([0-9a-fA-F]{4})(?![0-9a-fA-F])/g, (_, hex) =>
      String.fromCharCode(parseInt(hex, 16)),
    );
}

// 去掉 HTML 标签，折叠空白，得到搜索用的纯文本
function toPlainText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const files = walk(contentDir);
const articles = [];

for (const file of files) {
  const raw = fs.readFileSync(file, 'utf-8');
  const { data, content } = matter(raw);
  const chapter = Number(data.chapter);
  const section = Number(data.section);
  if (!chapter || !section) {
    console.warn(`[build-md] 跳过 ${path.relative(root, file)}：缺少 chapter / section 字段`);
    continue;
  }
  const key = `ch${chapter}-${section}`;
  const html = md.render(content);
  articles.push({
    key,
    chapter,
    section,
    title: String(data.title || `第${section}节`),
    icon: decodeJsEscapes(data.icon || ''),
    summary: String(data.summary || ''),
    keywords: Array.isArray(data.keywords) ? data.keywords.map(String) : [],
    // 可选：该文章所属「章」的显示名 / 图标（同一章任一篇写了就生效）
    chapterName: data.chapterName != null ? String(data.chapterName) : '',
    chapterIcon: decodeJsEscapes(data.chapterIcon != null ? data.chapterIcon : ''),
    html,
    plainText: toPlainText(html),
  });
}

// 按 章 -> 节 排序，保证导航/上一篇下一篇顺序稳定
articles.sort((a, b) => a.chapter - b.chapter || a.section - b.section);

const ts = `// AUTO-GENERATED by scripts/build-md.mjs —— 请勿手动编辑。
// 重新生成：npm run build:md
export interface MarkdownArticle {
  key: string
  chapter: number
  section: number
  title: string
  icon: string
  summary: string
  keywords: string[]
  chapterName: string   // 可选：该章在导航显示的名字（同一章任一篇写了即生效）
  chapterIcon: string   // 可选：该章在导航显示的图标（覆盖默认）
  html: string
  plainText: string
}

export const markdownArticles: MarkdownArticle[] = ${JSON.stringify(articles, null, 2)}

export function getMarkdownArticle(key: string): MarkdownArticle | undefined {
  return markdownArticles.find(a => a.key === key)
}
`;

fs.writeFileSync(outFile, ts, 'utf-8');
console.log(`[build-md] 已生成 ${articles.length} 篇文章 -> ${path.relative(root, outFile)}`);
